version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: terminado
    versions:
    - 0.9.2
  - dependency-name: lxml
    versions:
    - 4.6.2
  - dependency-name: cffi
    versions:
    - 1.14.4
  - dependency-name: httplib2
    versions:
    - 0.18.0
  - dependency-name: bleach
    versions:
    - 3.1.4
  - dependency-name: pillow
    versions:
    - 6.2.0
